language: cpp

install:
  - wget https://www.accellera.org/images/downloads/standards/systemc/systemc-2.3.3.tar.gz -O /tmp/systemc-2.3.3.tar.gz
  - tar -C /tmp -xvf /tmp/systemc-2.3.3.tar.gz
  - sudo ln -s /usr/bin/make /usr/bin/gmake
  - pushd /tmp/systemc-2.3.3 && mkdir objdir && cd objdir && ../configure --prefix=/tmp/systemc --with-unix-layout --enable-pthreads && gmake && sudo gmake install && popd
  - git clone https://github.com/werneazc/gsysc.git /tmp/gsysc
  - mkdir -p /tmp/gsysc/build 
  - pushd /tmp/gsysc && cmake -B build -S ./ -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
  - cmake --build ./build -- -j2 && popd
 
jobs:
  include:
    os: linux
    dist: focal
    compiler: clang
    env:
     - SYSTEMC_ROOT="/tmp/systemc"
     - GSYSC_ROOT="/tmp/gsysc"

    addons:
      apt:
        packages:
          - cmake
          - doxygen
          - qtbase5-dev

script:
  - mkdir build
  - cmake -B build -S ./ -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"
  - cd build && cmake --build ./ --config Release --target vcgra_only -- -j2
  - cmake --build ./ --config Release --target vcgra_prefetchers -- -j2
  - cmake --build ./ --config Release --target full_architecture  -- -j2
