language: cpp

install:
  - wget https://www.accellera.org/images/downloads/standards/systemc/systemc-2.3.3.tar.gz -O /tmp/systemc-2.3.3.tar.gz
  - tar -C /tmp -xvf /tmp/systemc-2.3.3.tar.gz
  - sudo ln -s /usr/bin/make /usr/bin/gmake
  - pushd /tmp/systemc-2.3.3 && mkdir objdir && cd objdir && ../configure --prefix=/tmp/systemc --with-unix-layout --enable-pthreads && gmake && sudo gmake install && popd

env:
  global:
    - SYSTEMC_ROOT=/tmp/systemc

jobs:
  include: 
    os: linux
    dist: focal
    compiler: clang
    env:
     - SYSTEMC_ROOT="/tmp/systemc"

    addons:
      apt:
        packages:
          - cmake
          - doxygen

script:
  - mkdir build
  - cmake -B build -S ./ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=14 -G "Unix Makefiles"
  - cd build && cmake --build ./ -- -j2
